let descriptions = {
    "variableName": "Variable name as defined in the source file.",
    "description": "Variable description. Defaults to an empty string.",
    "numchar": "Numchar attribute describes the classification of the data into two types `Character` and `Numeric`.",
    "nature": "Nature attribute describes the classification of data into `Nominal`,  `Ordinal`,  `Ratio`,  `Interval`, `Percentage`.",
    "binary": "Binary represents the data of variables in a form where they can only take two values `0` and `1`.",
    "interval": "Refers to the representation of the variables in certain intervals of values.",
    "time": "TODO: Description of the variable.",
    "invalidCount": "Invalid represents the count of missing values ( `NA`,`Null`, empty cells, etc) in the data of the given variable.",
    "validCount": "It refers to the data in the variable anything but not `invalid`.",
    "uniqueCount": "Uniques represents the count of unique values in the data of the given variable.",
    "median": "Median for a *numeric* variable. It represents the value lying at the midpoint of a frequency distribution.",
    "mean": "Mean for a *numeric* variable. It represents the average of the numbers in the data of the given variable. For non-numeric values, or if all values are missing, this value is set to null.",
    "max": "It is the maximum value among the values of the variable.",
    "min": "Min represents the minimum or least value in the data of the given variable.",
    "mode": "The value of the most frequently occurring variable.  If more than multiple variable share the highest number of occurrences, up to the first 5 are displayed.",
    "modeFreq": "It is a part of mode which represents the `count/frequency` of the mode of the given variable.",
    "fewestValues": "fewest represents the value of the least frequently occurring variable. If more than multiple variable share the highest number of occurrences, up to the first 5 are displayed.",
    "fewestFreq": "It is a part of fewest which represents the `count/frequency` of the fewest of the given variable.",
    "midpoint": "TODO: Description of the variable.",
    "midpointFreq": "It is a part of mid which represents the `count/frequency` of the mid of the given variable.",
    "stdDev": "sd represents the `standard deviation`, which is the measure of how spread out the numbers are in the data.",
    "herfindahlIndex": "TODO: Description of the variable.",
    "plotValues": "It represents the array of the values to draw the `bar` plot.",
    "plotType": "describes the type of plot on the basis of the data of the variable. It is mainly classified as `Bar` and `Continuous`.",
    "plotX": "plotx describes the x-coordinates of the plot drawn using the data of the given variable.",
    "plotY": "ploty describes the y-coordinates of the plot drawn using the data of the given variable.",
    "cdfPlotType": "CDF : cumulative distribution function. The cdf plot represent the cumulative distribution of the data of the variable.",
    "cdfPlotX": "cdfplotx describes the x-coordinates of the `cdf plot` drawn using the data of the given variable.",
    "cdfPlotY": "cdfploty describes the x-coordinates of the `cdf plot` drawn using the data of the given variable.",
    "defaultInterval": "It represents the user input for the interval from the interface if user wants the variable to have default interval. The definition of this remains the same as interval.",
    "defaultNumchar": "It represents the user input for the numchar from the interface if user wants the variable to have default numchar. The definition of this remains the same as numchar",
    "defaultNature": "It represents the user input for the nature from the interface if user wants the variable to have default nature. The definition of this remains the same as nature",
    "defaultBinary": "It represents the user input for the binary from the interface if user wants the variable to have default binary. The definition of this remains the same as binary",
    "defaultTime": "It represents the user input for the time from the interface if user wants the variable to have default time. The definition of this remains the same as time"
};

export default descriptions;